### ISSUE TITLE
nif . example don't work

### ISSUE THREAD

**Issue by benoitc** [davisp/emonk#2]
enlil:test_emonk benoitc$ ERL_LIBS=~/src/test_emonk/deps/emonk/src erl -pa deps/ibrowse/ebin
Erlang R13B04 (erts-5.7.5) [source] [64-bit] [smp:2:2] [rq:2] [async-threads:0] [hipe] [kernel-poll:false]

Eshell V5.7.5  (abort with ^G)
1> {ok, Port} = emonk:new().

=ERROR REPORT==== 7-Apr-2010::16:06:14 ===
The on_load function for module emonk returned {error,
                                                {load_failed,
                                                 "Failed to load NIF library: 'dlopen(/Users/benoitc/src/test_emonk/deps/emonk/src/emonk/priv/emonk_drv.so, 2): image not found'"}}
*\* exception error: undefined function emonk:new/0

I just did ./configure && make in emonk, beam are here but no so.

**Comment by davisp** [comment]
The make file is kind of hackish for this. If you run `make check` it copies the so library from ./src/emonk/priv/.libs/ to ./src/emonk/priv/ which is required to make that work.

Later today I'll swap that out for rebar to make that easier.
